burgershop/burger_settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('Бургеры/', include('list_product.urls')),
    path('Корзина/', include('cart.urls')),
    path('Профиль/', include('user_profile.urls')),
    path('Заказы/', include('orders.urls')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

burgershop/burgershop/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

burgershop/cart/urls.py
from django.urls import path
from .views import CartView


urlpatterns = [
 path('', CartView.as_view(), name='user-cart')
]

burgershop/user_profile/urls.py
from django.urls import path
from .views import UserProfileDetail, UserProfileUpdate


urlpatterns = [
    path('', UserProfileDetail.as_view(), name='user-profile'),
    path('Обновить/', UserProfileUpdate.as_view(), name='user-update'),
]

burgershop/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


class Profile(models.Model):
    """Model User profile."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=1000, verbose_name='Информация о пользователе')
    img = models.ImageField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('user-profile', args=[str(self.id)])

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        """
        Creating a model profile when registering a user.
        """
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        """
        Update model profile.
        """
        instance.profile.save()

burgershop/user_profile/forms.py
from django import forms
from .models import Profile, User


class UserForm(forms.ModelForm):
    pass

    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class UserProfileForm(forms.ModelForm):
    pass

    class Meta:
        model = Profile
        fields = ('description', 'img')

burgershop/user_profile/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from .forms import UserForm, UserProfileForm
from .service import save_user_profile


class UserProfileDetail(LoginRequiredMixin, View):

    def get(self, request):
        """"""
        return render(request, 'user_profile/profile.html', context={
                                                                'profile': request.user.profile,
                                                                'user': request.user,
                                                                    })


class UserProfileUpdate(LoginRequiredMixin, View):

    def get(self, request):
        """Displays a page with user data."""
        return render(request, 'user_profile/profile_update.html', context={
                                                                        'profile': request.user.profile,
                                                                        'user': request.user,
                                                                           })

    def post(self, request):
        """IF the forms are valid saves the data about the user ELSE doesn't change anything."""
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            save_user_profile(user_form, profile_form)

            return redirect('user-profile')

        else:
            return redirect('user-change')

burgershop/templates/user_profile/profile.html
{% extends 'base.html' %}

{% block content %}

<h2>{{  user.username }}</h2>
<p>{{ profile.description }}</p>
<p><a href="{% url 'user-update' %}">Обновить профиль.</a></p>

{% endblock %}

burgershop/templates/user_profile/profile_update.html
{% extends 'base.html' %}

{% block content %}

   <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_first_name">Имя:</label>
            <input type="text" name="first_name" id="id_first_name" value="{{ user.first_name }}">

            <p><label for="id_last_name">Фамилия:</label>
            <input type="text" name="last_name" id="id_last_name" value="{{ user.last_name}}"></p>

            <p><label for="id_description">Описание:</label>
            <textarea name="description" id="id_description">{{ profile.description }}</textarea></p>

            <p><label for="id_img">Аватар вашего профиля:</label>
            <input type="file" name="img" id="id_img"></p>

            <p><button type="submit">Сохранить</button></p>
        </form>

{% endblock %}